# Generated by Django 4.2.18 on 2025-09-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimlivedeploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
            ],
        ),
    ]
